//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.Accounts1 = new HashSet<Accounts>();
        }
    
        public int ID { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> Parent { get; set; }
        public int ParentLevel { get; set; }
        public Nullable<bool> VoucherEntry { get; set; }
        public bool FinalAccount { get; set; }
        public int AccountGroup { get; set; }
        public Nullable<int> SubGroup { get; set; }
        public Nullable<int> AccCategory { get; set; }
        public Nullable<bool> ShowChild { get; set; }
        public Nullable<bool> ISDefault { get; set; }
        public Nullable<bool> AllowEntry { get; set; }
        public bool InActive { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<long> UserTrackID { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> BranchID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<int> AOrderNo { get; set; }
        public Nullable<int> CCID { get; set; }
        public Nullable<bool> InVisible { get; set; }
        public Nullable<decimal> SortField { get; set; }
        public Nullable<bool> ShowRow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounts> Accounts1 { get; set; }
        public virtual Accounts Accounts2 { get; set; }
    }
}
