//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_LibraryBookMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School_LibraryBookMaster()
        {
            this.School_LibraryBookDetails = new HashSet<School_LibraryBookDetails>();
        }
    
        public int BookMastID { get; set; }
        public string BookCode { get; set; }
        public string CallNo1P1 { get; set; }
        public string CallNo1P2 { get; set; }
        public string CallNo1P3 { get; set; }
        public string CallNo2 { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Author1 { get; set; }
        public string Author2 { get; set; }
        public string Series { get; set; }
        public string Copies { get; set; }
        public string Publisher { get; set; }
        public string ISBN { get; set; }
        public string Barcode { get; set; }
        public string Volume { get; set; }
        public string Remarks { get; set; }
        public string BillNoold { get; set; }
        public string Callnoold { get; set; }
        public string Category { get; set; }
        public string ArticleType { get; set; }
        public string ArticleCategory { get; set; }
        public string GMD { get; set; }
        public string CallNo { get; set; }
        public string language { get; set; }
        public string description { get; set; }
        public byte[] img { get; set; }
        public Nullable<System.DateTime> dateofentry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School_LibraryBookDetails> School_LibraryBookDetails { get; set; }
    }
}
