//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_LibraryBookDetails
    {
        public int BookID { get; set; }
        public int BookMastID { get; set; }
        public string BookSubCode { get; set; }
        public string CallNo3 { get; set; }
        public string AccessionNo { get; set; }
        public string Edition { get; set; }
        public string PageNo { get; set; }
        public string PublishedYear { get; set; }
        public Nullable<decimal> BasicValue { get; set; }
        public string Currency { get; set; }
        public string PurchaseDate { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string InOut { get; set; }
        public string CostinDhs { get; set; }
        public string Remarks { get; set; }
        public string IssueStatus { get; set; }
        public string Barcode { get; set; }
        public string Count { get; set; }
        public string Callnoold { get; set; }
        public string billno { get; set; }
        public string category { get; set; }
        public string Shift { get; set; }
        public string PlaceOfPublication { get; set; }
        public string BookLanguage { get; set; }
        public string StockStatus { get; set; }
    
        public virtual School_LibraryBookMaster School_LibraryBookMaster { get; set; }
    }
}
