//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_LibraryIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School_LibraryIssue()
        {
            this.School_LibraryReturn = new HashSet<School_LibraryReturn>();
        }
    
        public int ID { get; set; }
        public string IssueNo { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string AccessionNo { get; set; }
        public string Title { get; set; }
        public string SubName { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<long> MemberID { get; set; }
        public string MemberType { get; set; }
        public string IssueStatus { get; set; }
        public string Class { get; set; }
        public Nullable<decimal> Fine { get; set; }
        public Nullable<int> RID { get; set; }
        public string Shift { get; set; }
        public Nullable<int> MaxDays { get; set; }
        public Nullable<int> BookID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<School_LibraryReturn> School_LibraryReturn { get; set; }
    }
}
