//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_LibraryReturn
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string RetunNo { get; set; }
        public string Remarks { get; set; }
        public string ModifiedUser { get; set; }
        public string Modifiedtime { get; set; }
        public Nullable<int> IssueId { get; set; }
        public Nullable<System.DateTime> RenewalDateOld { get; set; }
        public string RType { get; set; }
    
        public virtual School_LibraryIssue School_LibraryIssue { get; set; }
    }
}
